### ISSUE TITLE
Converted graphs not showing

### ISSUE THREAD

**Issue by desparza22** [hmc-alpaqa/metrinome#19]
Thank you for sharing this project! I didn't list this as a bug because I wasn't sure if maybe I was doing something wrong. I seem to run into trouble inside of the Path Complexity REPL. I was able to convert the first file I tried (a Java file), but I noticed the graph said "Lines of code: None", so I decided to try a second to see if maybe there was an issue with the first. Converting the second file resulted in "Converted Successfully", but then unlike the first, no name for the graph was printed to the terminal. I tried "list graphs", and got "No graphs available". The same thing happened when I quit and tried again. Maybe it is an issue with the file itself, but it is a very simple file in terms of structure, and very similar to the first which converted successfully. The only difference between the two is that the first calls static functions whereas the second creates an object and calls functions on the object. All functions and variables in each file are contained within a single object. Thank you for your help! Let me know if I can further explain any of these issues.

**Comment by gabrielbessler** [comment]
Thanks for submitting this. The LoC metric is currently not available for Java, so the "Lines of code: None" should be fine. I'll think about a way to make this clearer in the REPL (it might make more sense not to display metrics that aren't supported for a given language). 

In terms of the error, would it be possible for you to post the source code for the file you tried to convert that resulted in the "no graphs available" error? It's very possible there was some error in converting the file due to the structure of the code. Also, running the REPL in debug mode might provide useful info (`python main.py --debug`)

**Comment by desparza22** [comment]
The debug mode was very helpful, thank you! I should have tried that first. It turns out there was just an issue with multiple files of mine having the same name, and I was editing the wrong one. I will close this.
