### ISSUE TITLE
Unable to convert

### ISSUE THREAD

**Issue by UsmanGohar** [hmc-alpaqa/metrinome#22]
Hello, I am having trouble using the convert command. I am simply trying to convert the python example given (for starters) but it keeps saying "Could not get files from:  test.py". I am probably missing a trick here. Do you have an idea?

**Comment by JoshCordova** [comment]
We just added support for relative filepaths, which should help with your issue. We previously only supported absolute paths. Hope that helps!

**Comment by UsmanGohar** [comment]
Thank you! It worked using the absolute path, still buggy for the relative path (could be just on my end though)

Quick questions,

1) Are the generated CFGs block-level or statement-level? (Where would I need to play around to get block-level?)
2) How can I map the code to the dot files? (Can I possibly add, what the label ids correspond to, in the code? e.g in the snapshot below, where would I need to make changes to add e.g what 0,1,....6 refer to from the code)

Thank you so much for such a prompt response!

![image](https://user-images.githubusercontent.com/23078706/107295595-506c0700-6a35-11eb-9c13-9095c2c97506.png)

**Comment by gabrielbessler** [comment]
Thanks for the questions! 

The relative path changes were pushed yesterday and seem to work for me but I'll test them more rigorously later this week. If absolute paths work for you I would just use those for now.

With respect to the questions: 

1. The generated CFGs differ by programming language (C/C++ is block level), but for Python the generated CFGs are statement level - you can take a look at the code [here](https://github.com/hmc-alpaqa/metrinome/blob/develop/src/lang_to_cfg/python.py). The `FunctionVisitor` automatically calls the appropriate `visit_<T>` functions as it traverses the (AST of the) code.  The easiest way to get block-level CFGs for Python would probably be to simplify the CFG after it's been generated. Alternatively, it would be possible to modify the functions that deal with statements that do not affect control flow (e.g. `visit_Pass`, `visit_Assign`, `visit_Expr`) so that they do not add new vertices to the CFG. 

2. Again, this differs by programming language, but I'm assuming you mean for Python - feel free to correct me if I'm wrong. This is currently not possible for Python, but adding it would just be a matter of adding metadata to a node when it's created in a `visit_<T>` function. This metadata would then have to be propagated to the CFG Metadata object. Note that for the C++ converter, we go from `source code -> .dot file -> simplified .dot file (remove labels) -> CFG`, but for Python it's `source code -> CFG -> .dot file`, so to get these labels in the .dot file itself for Python the exporter which turns `CFG -> .dot` would also have to understand this new metadata.

These both seem like useful features that we hadn't thought of, so I'd be willing to implement them, although it might be a few weeks before I can get around to it (if you feel like modifying the code to get it working I'm happy to answer any more questions😃)

**Comment by UsmanGohar** [comment]
Thank you again for the response!

1) Actually, I'm looking to generate graphs for C & Java, so if both of them are block-level, that is music to my ears! :)
2) I will definitely take you up on that offer. I will try to get my hands dirty with the code to see if can add these changes. However, based on your comment, C/Java might have this/easier to modify? Either way, I would really appreciate it if you could point me in the direction i.e. to add the code snippets to the .dot file

These are very useful features, especially for my case. I really appreciate you taking the time out now and for sharing your work~

**Comment by UsmanGohar** [comment]
Another quick question. I just tried a simple Java program (below) and it converts successfully but I don't see any output .dot file in the directory  (/app/code/tmp_dot). Am I doing something wrong? I have used the debugger and it says it outputs the files but I don't see them. I will test C as well. I really appreciate both of your help!

**Update**: When I use show, it picks up the graphs but not using export

![image](https://user-images.githubusercontent.com/23078706/107439185-4d394f80-6af7-11eb-80fc-6f10f2490a20.png)

It says the following:

![image](https://user-images.githubusercontent.com/23078706/107448487-61854880-6b07-11eb-8623-5d1ed3ae2832.png)

**Comment by gabrielbessler** [comment]
W.r.t. your first question, the easiest one to modify (by far) would be C. The java converter is some java code that we inherited and is ~5 years old - we just run the compiled jar from the repl. The to_graph method of [CPPConvert](https://github.com/hmc-alpaqa/metrinome/blob/develop/src/lang_to_cfg/cpp.py) handles all of the logic from `src -> CFG`. For what you're interested in, you probably want to edit 'convert_to_standard_format' in CPPConvert. This parses the original .dot file and removes all of additional metadata (such as what code each block corresponds to). E.g. parse_original could return the extra metadata. Let me know if this seems like a reasonable starting point. 

Since for Java and C++ we go `src -> .dot -> CFG`, the .dot files are then deleted after the CFG is created. The "Created /app/code/.../HeapSort_heapify_0_basic.dot" is actually meant to indicate that a Graph object was created, not a dot file. I've updated the output message to be a bit more clear about this. There seems to be an issue here which is that the graph is getting the name of the generated dot file, instead of something like "HeapSort_heapify_graph". We'll look into this and fix it some time this week.

do_export was breaking because the graph name had '/' in it. I've added a temporary workaround (it'll just replace '/' in the graph name with '_'). The graph names end up being super weird but it'll work until we push the graph name fix.

![image](https://user-images.githubusercontent.com/12840669/107469418-8f29bc00-6b1e-11eb-90ee-06c74539b2e6.png)

**Comment by UsmanGohar** [comment]
Awesome! I will start from there and bug you if I can't figure it out. 

P.S just to confirm, C & Java are both block-based right?

**Comment by JoshCordova** [comment]
That's correct. Also to get a look at the original .dot files, you can comment out Env.cleanTemps() on line 61 in cpp.py and they'll be in /app/code/tmp. The standard format .dot files will be in /app/code/tmp_dot. Just make sure to empty the folders in between each conversion or you'll get a bunch of duplicate graphs.

**Comment by UsmanGohar** [comment]
So I did some digging around today. The original.dot file seems to be the one below, correct me if I am wrong. I followed the code to this parser, where I think the action is https://github.com/hmc-alpaqa/metrinome/blob/f9c727ebbeb865d03549b0b393b32bcd7d5fcd88/src/tests/coreutils_experiment.py#L19

I probably don't have the knowledge, if this is a silly question, but how do I extract the code from this original .dot file? I can see the parser pulling the nodes & the edges using -> etc. But I am not following the code part. Thanks a bunch, guys. I can't appreciate your help enough!

![image](https://user-images.githubusercontent.com/23078706/107898801-5022ae80-6f02-11eb-98be-2b78713394ea.png)

**Comment by JoshCordova** [comment]
The parse_original() that the REPL uses is in cpp.py, our bad for leaving that in the experiment file. We haven't been able to directly extract the source code from the dot files since LLVM creates them from bitcode rather than directly from the source file. We'd likely have to construct these CFGs by parsing the source files ourselves, similar to the python converter.

**Comment by UsmanGohar** [comment]
Yeah, it seemed like bitcode. Constructing the CFGs by parsing the source files won't be as comprehensive, would they? Unlike the python converter, it will have to be a pretty big effort to capture all the various C code keywords/features?

Would it be the same with Java as well (not getting the source blocks directly)? I dug a bit in the java.py. I'll try looking into the temp files just like C
